### ISSUE TITLE
Any crate examples?

### ISSUE THREAD

**Issue by kon3gor** [kotauskas/interprocess#39]
HI, I've never worked with IPC and I'd like to use this crate to solve a simple problem - I just need a way to tell my daemon to start some routine. But there is no a single example of using this crate even tho there is links like [this](https://github.com/kotauskas/interprocess/blob/main/examples/local_socket/server.rs) in the docs. I've also tried to obtain some knowledge from tests, but it's quite difficult for me. Can you provide some basic examples?

**Comment by kon3gor** [comment]
Guess I've used the wrong form, it should probably be improvement :/

**Comment by kotauskas** [comment]
The docs you see in the publicly available Crates.io version, 1.2.1, link to files which used to be where the examples lived but have since been removed in favor of moving the examples back into documentation text directly, as they were in an earlier version. This change will be released as part of 2.0.0.

Until then, you can [browse the examples from the commit history](https://github.com/kotauskas/interprocess/tree/4cdf61265fec855d7e0ce997fc98f1829e29c861/examples).

**Comment by kon3gor** [comment]
I see, okay, thanks for info
