### ISSUE TITLE
UNIX Socket/Win Pipe authentication support

### ISSUE THREAD

**Issue by Mart-Bogdan** [kotauskas/interprocess#4]
Both windows and unix provides some means of authenticating clients. It's so called peer authentication on UNIX.

UNIX gives uid gid of user of other side. Windows allows to impersonate user(given proper flags was passed on socket creation and connection from client). After that user id and name could be retrived. 

And both OSes allows to get PID of the client.

I've looked through the docs and haven't find above functionality.

**Comment by kotauskas** [comment]
The functionality exists for Unix in the form of [`AncillaryData::Credentials`]: you can both send and receive those with ease, and impersonation is actually supported because you can fill out arbitrary values there if you're the root user.

If I remember correctly, there's also another way on Unix which does not require cooperation between two ends, where one end can simply query the PID of the peer, without support for impersonation. It's not supported yet, but it would be easy to implement it.

On Windows, named pipes require some cleaning up in the documentation and are missing the peer authentication feature entirely, which shouldn't be too hard to improve as well.

It would also be pretty neat to expose this functionality in `local_socket` itself, which should just be a matter of boilerplate.

[`AncillaryData::Credentials`]: https://docs.rs/interprocess/1.0.1/interprocess/os/unix/udsocket/enum.AncillaryData.html#variant.Credentials " "

**Comment by kotauskas** [comment]
This functionality is implemented on the `master` branch but not yet released, since I want a few other things in 1.1.0 which aren't quite ready. I'm finishing those really soon, so it's almost done.

**Comment by kotauskas** [comment]
1.1.0 has been released, you can check the [release notes] for more details on how to use this feature.

[release notes]: https://github.com/kotauskas/interprocess/releases/tag/1.1.0 " "
