### ISSUE TITLE
Way to know if there are bytes to read from LocalSocketStream

### ISSUE THREAD

**Issue by DjDeveloperr** [kotauskas/interprocess#5]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to read completely what is there in the LocalSocketStream. I do this in loop, but when it completes, and I attempt to call read, it just gets blocked there.

**Describe the solution you'd like**
A way to know how much bytes are there to read or at least to know if there is something to read?

**Describe alternatives you've considered**
No alternative... currently not able to do anything about it.

**Additional context**
Nothing, was just making a Deno plugin for IPC.

**Comment by kotauskas** [comment]
This behavior is actually consistent with normal sockets. It intentionally blocks to wait for more data, since the server never closes the connection. You should either read until a specific "end communication" marker in the protocol (if there even is a protocol both sides agree on), or use the nonblocking mode, which returns the `WouldBlock` error if you try to do something that would block otherwise. Speaking of, I've just implemented support for nonblocking mode, it's available on the `master` branch. I'm still finishing up the 1.1.0 release, there are two small things I have in mind, which I will hopefully do really soon.

**Comment by DjDeveloperr** [comment]
I'll look into using nonblocking mode, thanks.

**Comment by kotauskas** [comment]
1.1.0 is out, so you can use nonblocking mode from the Crates.io version; see the [release notes].

[release notes]: https://github.com/kotauskas/interprocess/releases/tag/1.1.0 " "
