### ISSUE TITLE
Error on flushing

### ISSUE THREAD

**Issue by 0e4ef622** [kotauskas/interprocess#58]
**Describe the bug**
Attempting to call `flush` on a `LocalSocketStream` returns an error. This makes them unusable with libraries that expect `flush` to not error, like `tonic`.

**To Reproduce**
```rs
use interprocess::local_socket::{
    tokio::prelude::LocalSocketStream,
    traits::tokio::{Listener, Stream},
    ListenerOptions, NameTypeSupport, ToFsName, ToNsName,
};
use tokio::io::{AsyncReadExt, AsyncWriteExt};

#[tokio::main]
async fn main() {
    tokio::join! {
        server(),
        client(),
    };
}

pub async fn server() {
    let name = match NameTypeSupport::query() {
        NameTypeSupport::OnlyFs => "sock".to_fs_name().unwrap(),
        NameTypeSupport::OnlyNs | NameTypeSupport::Both => "sock".to_ns_name().unwrap(),
    };

    let listener = ListenerOptions::new().name(name).create_tokio().unwrap();

    // Wait for client to connect
    let connection = listener.accept().await.unwrap();

    let mut buf = *b"abcde";
    let mut connection = &connection;
    connection.read_exact(&mut buf[..]).await.unwrap();
    println!("Got {:?}", std::str::from_utf8(&buf));
}

pub async fn client() {
    let name = match NameTypeSupport::query() {
        NameTypeSupport::OnlyFs => "sock".to_fs_name().unwrap(),
        NameTypeSupport::OnlyNs | NameTypeSupport::Both => "sock".to_ns_name().unwrap(),
    };
    let mut connection = LocalSocketStream::connect(name).await.unwrap();
    let buf = *b"hello";
    connection.write_all(&buf).await.unwrap();
    connection.flush().await.unwrap();
}

```

**Expected behavior**
No error.

**Screenshots**

**Additional context**

**Comment by kotauskas** [comment]
Although I have not finalized this behavior, it is my impression that the standard library's choice to silently succeed in `<TcpStream as Write>::flush()` is a mistake.

Flushing is a filesystem operation with write durability assurance and write fence semantics, and it's not something that should normally occur in code that deals with communication channels, since there is neither a need for write fences nor a portable way to ensure durability. The deficient platform here is Unix, and that is in some sense understandable: the best one could do with TCP ACK is ensure that the data has reached the remote host (not that it's been *read* by the remote *program*), and so `AF_UNIX` neglects to natively implement this for the sake of consistency or simply due to an oversight.

The Windows side of things actually has a way to block until the client has received all the data, invoked via `FlushFileBuffers()`, but local sockets on Windows deliberately hide that feature for the sake of portability.

Do you happen to know any details on why Tonic explicitly uses `.flush()` whilst expecting it to do absolutely nothing without an error?

**Comment by 0e4ef622** [comment]
I took a deeper look and it seems like the flushing actually comes from either `hyper` or `h2`. As for possible reasons why, flushing is necessary when writing to a [buffered writer](https://docs.rs/tokio/latest/tokio/io/struct.BufWriter.html). In general, I don't think erroring on flush is the right thing to do since it breaks existing code meant to be generic over IO. Maybe in a perfect world there would be a method to query whether flush actually does anything, similar to [`is_write_vectored`](https://doc.rust-lang.org/std/io/trait.Write.html#method.is_write_vectored) in the `Write` trait.

**Comment by kotauskas** [comment]
That makes sense. I don't suppose I can do much about the `.flush()` protocol meaning too many things at once. Behavior is now consistent with the standard library.
