### ISSUE TITLE
Document how to initiate interprocess connections

### ISSUE THREAD

**Issue by mstange** [kotauskas/interprocess#60]
I have a receiver and a sender. But they're both in my current process. How do I get the receiver to be in a different process?

It would be nice if the documentation answered this question, for every supported OS and every connection type.

**Comment by kotauskas** [comment]
I assume, since you mention receivers and senders, that you're talking about unnamed pipes. Those are primarily meant for communication between a parent process (supervisor, manager, dispatcher, frontend, etc.) and a child process (sub-task, host process of a lengthy computation, extension, backend, etc.). The way you get either side of the connection to end up at the child process is a little formulaic, but simple:
1. Create the unnamed pipe sender-receiver pair
2. Via `AsRawHandle`/`AsRawFd`, query the handle or file descriptor value of the connection end that you want to use in the child process
3. Spawn the child process with a command-line argument containing the handle/FD value serialized to a string
4. In the child process, parse the command-line argument, recover the handle and use `FromRawHandle`/`FromRawFd` to obtain the connection end

This works because all unnamed pipes created by Interprocess have inheritable handles.

Note that the standard library allows you to pipe the `stdout` of the child process to the parent, bypassing the entirety of Interprocess. This is enough in many cases and the main appeal of Interprocess comes from situations when this type of IPC isn't applicable, in which case you turn to local sockets.

I will make sure to include a similar explanation to the unnamed pipe documentation in version 2.0.1.

**Comment by kotauskas** [comment]
2.0.1 is up.

**Comment by mstange** [comment]
Thanks so much for the fast reply!

> This works because all unnamed pipes created by Interprocess have inheritable handles.

This was the crucial piece of information I was missing. Also I didn't realize that a raw handle on Windows is still just a u32 number.

**Comment by kotauskas** [comment]
> raw handle on Windows is still just a u32 number
@mstange it's more of a `usize` canonically printed in hexadecimal that the standard library and `Windows.h` unhelpfully define as `*mut c_void`, but `windows_sys` defines an `isize`. The safest thing to do is to serialize the return value of `AsRawHandle` immediately without any further casts.

**Comment by mstange** [comment]
How should I serialize it without any casts?

**Comment by kotauskas** [comment]
@mstange [`Pointer`](<https://doc.rust-lang.org/std/fmt/trait.Pointer.html>) formatting (`format!("{:p}", my_half.as_raw_handle())`).

**Comment by mstange** [comment]
I would never have guessed that. Thanks!

**Comment by mstange** [comment]
And then how do you get back a `HANDLE` from this string?
