### ISSUE TITLE
Owning version of `Incoming`

### ISSUE THREAD

**Issue by DaniPopes** [kotauskas/interprocess#64]
**Is your feature request related to a problem? Please describe.**
I cannot create a `Listener` and return a `impl Iterator`/`impl AsyncIterator` inside of the same function because `ListenerExt::incoming` borrows the `Listener`.

**Describe the solution you'd like**
Add `into_incoming` (or something similar) to `ListenerExt` as a owned alternative to `Incoming`.

**Describe alternatives you've considered**
I could implement this myself (or `Box::leak(Box::new(_))` :smile:) but I think this better belongs here.

**Additional context**
N/A

**Comment by kotauskas** [comment]
As of 2.1.0, all local socket `Listener`s implement `Iterator` by itself, so returning an `impl Iterator` is as simple as returning the listener itself. An analogous feature is present for async local sockets.

**Comment by DaniPopes** [comment]
Thanks!

**Comment by DaniPopes** [comment]
Just tried this out, I believe the async version does not work because accept should be stored and polled until completion, whereas the current implementation will call accept on every poll https://github.com/kotauskas/interprocess/blob/b79d3636152158f7a8977f8043188e89446916c5/src/os/windows/named_pipe/local_socket/tokio/listener.rs#L40-L48

**Comment by kotauskas** [comment]
While fixing this bug, I've discovered that `Incoming` itself is broken for async local sockets. As such, I have removed all of the `AsyncIterator` implementations, including async `Incoming` itself.

I don't see a good way to tackle this problem, since `Stream` (`AsyncIterator`) by design requires the locals of the future to be stored within the stream itself. Getting a projection to the concrete type behind a given function's RPIT is impossible, and hence storing the future type a given `async fn` returns without introducing a type argument to the containing type is also impossible.

Note that this flaw of `Stream` is primarily due to Rust not supporting GATs when the trait first came to be.
