### ISSUE TITLE
Question: Are my interprocess data transmission speeds reasonable on Windows?

### ISSUE THREAD

**Issue by brookman** [kotauskas/interprocess#73]
Hello there,

I'm experimenting with various approaches to transmitting data between processes on Windows, aiming for the highest possible throughput. Specifically, I'm transferring 200 MiB of data and timing how long it takes.

Using the `interprocess` crate, I achieved a transmission time of ~85 ms between two test executables, which translates to around 2.3 GiB/s. With the `shared_memory` crate, the transfer time is ~70 ms for the same data size (also on Windows).

Are these performance numbers reasonable? I was expecting significantly higher speeds, especially considering this seems like a simple memory copy operation (from my naive point of view). Could this indicate a hardware limitation, or am I overlooking something in my approach?

System Specs:

- Dell Precision 7560
- Intel i9-11950H
- 64 GB RAM @ 3200 MHz
- Windows 11 Enterprise

Thank you for your insights!

**Comment by kotauskas** [comment]
Given the shared memory figure, I'd say named pipes are performing much, much faster than expected. Note the tremendous overhead of named pipes due to the highly complex I/O stack of Windows, the numerous context switches and the internal memory management of the kernel and the Win32 implementation.
